### ISSUE TITLE
Problem with Builder Git source URI ending in '.git'

### ISSUE THREAD

**Issue by mjuenema** [objectified/vdist#2]
The _buildscript.sh_ fails to change into the right directory if the URI for Git sources ends in `.git`. The `git clone https://github.com/myuser/myapp.git` command works with either URI (tested with Github) but the _buildscript.sh_ will attempt to change into the directory `myapp.git` which won't exist. While this is easy to work-around (once you work it out!) it would be nice to deal with this transparently in _buildscript.sh_ or _vdist.sources.git()_.

**Working:**

``` python
builder.add_build(
    app='myapp',
    version='1.0',
    source=git(
        uri='https://github.com/myuser/myapp',
        branch='develop'
    ),
    profile='centos6',
    build_deps=[],
    runtime_deps=[]
)
```

**Not working:**

``` python
builder.add_build(
    app='myapp',
    version='1.0',
    source=git(
        uri='https://github.com/myuser/myapp.git',    # creates myapp/ not myapp.git/
        branch='develop'
    ),
    profile='centos6',
    build_deps=[],
    runtime_deps=[]
)
```

**Comment by objectified** [comment]
Thanks for reporting this, and for using vdist!

I've solved the issue (see referenced commit) and created a few tests for it. If you still experience problems with it, let me know.
