### ISSUE TITLE
I don't get how vdist works when run against a project with setup.py

### ISSUE THREAD

**Issue by dante-signal31** [objectified/vdist#5]
I'm trying to package [geolocate](https://github.com/dante-signal31/geolocate), but I haven't got an useful deployment package because of what I'm going to describe you.

My [vdist](https://github.com/objectified/vdist/) script is like this:

``` python

from vdist.builder import Builder
from vdist.source import git

builder = Builder()

builder.add_build(
    app='geolocate',
    version='1.3.0',
    source=git(
        uri='https://github.com/dante-signal31/geolocate',
        branch='master'
    ),
    profile='ubuntu-trusty',
    compile_python=True,
    compile_python_version='3.4.3',
    fpm_args='--maintainer dante.signal31@gmail.com -a native --url https://github.com/dante-signal31/geolocate --description "This program accepts any text and searchs inside every IP address. With each of those IP addresses, geolocate queries Maxmind GeoIP database to look for the city and country where IP address or URL is located. Geolocate is designed to be used in console with pipes and redirections along with applications like traceroute, nslookup, etc. " --license BSD-3 --category net',
    requirements_path='/REQUIREMENTS.txt'
)

builder.build()
```

As far as I've found out, vdist does next steps:
1. Launch a Docker container.
2. Updates that container OS packages.
3. Installs [fpm](https://github.com/jordansissel/fpm).
4. Downloads, compiles and install a Python interpreter with given version.
5. Creates (if it doesn't exist yet) an /opt folder.
6. Clones given git repository inside /opt folder.
7. Creates a virtualenv with compiled Python inside /opt project folder.
8. Activates virtualenv.
9. Installs with pip all Python Package Index dependencies inside virtualenv.
10. If project has a setup.py then runs it to install project inside virtualenv.
11. Packages with fpm project folder and compiled python folder.
12. Leaves compiled package in container shared folder.
13. Shutdowns docker container.

OK, I understand the overall process but I don't get steps 10 and 11 (mainly 11):
- If you have run _"python setup.py install"_, project folder becomes useless because runnable application is actually installed in your virtualenv's _lib/python/site-packages_. As vdist seems to work, you end with your _setup.py_ and _requirements.txt_ being included in your deployment package, which are something I think you surely don't want in your debian package.
- If vdist packages your compiled python folder but doesn't include anyhow your virtualenv's _site-packages_ folder, pip downloaded dependencies shouldn't be lost?. 
- Vdist seems to focus on packaging project folder (that I said I think is mainly useless after setup's install) but doesn't seems to take in count virtualenv _site-packages_ folder generated by setup install (which in my humble opinion is what you'd likely want to deploy). Actually, my _setup.py_ generates too a geolocate launcher that is placed in virtualenv _bin_ folder. I don't know how to include that launcher in generated package. 
- Suppose you end with a debian package that installs two folder: your application and the python virtualenv folder needed to run your application. How do you automate the installed virtualenv activation when your application launcher is called?.

Thanks for your time!

**Comment by objectified** [comment]
Hi,

Let me get this out of the way first: vdist really isn't meant to create any sort of "official" packages. It's merely a convenient tool for companies/individuals to distribute their applications onto their servers. I'm not sure if your perception differs (and it _can_ of course be used for anything), but I just wanted to have said that.

As for your questions:
- the reason that vdist performs a `python setup.py install` is not so much for installing the application into site-packages (although it does that) but it is done to make sure that things like setuptools' "entry points" are created. A number of applications need those, so it's convenient that vdist creates them. We could make it optional, if this default behavior gets in your way.
- the virtualenv is created _inside_ the application's directory. This means that there is no separate folder for the virtualenv contents, they're in the same place (imagine the effect of performing `virtualenv .` inside the project directory - that's what vdist does) So it does in fact include the site-packages directory.

I hope I cleared up a few things by this. If not, ask away.

**Comment by dante-signal31** [comment]
I've been doing tests with application I want to package ([geolocate](https://github.com/dante-signal31/geolocate)). Its _setup.py_ is quite simple but it has an entry point. 

The thing is that, as far as I've found out examining generated debian package content, created entry point does not end in application virtualenv's _bin_ folder but in _/opt/vdist-python_'s one. The same happens with the application itself (and its dependencies) because it ends in _/opt/vdist-python_'s _site-packages_ folder instead of in virtualenv's one. I guess all of this happens because _setup.py install_ and pip are called using _/opt/vdist-python_ interpreter instead of the one in the virtualenv.

Along that, I've installed generated package in a testing virtual machine and I've been able to run my application from the "executable" (the entry point) placed in _/opt/vdist-python/bin_ even after removing _/opt/geolocate_ folder.

I'm just trying to figure out the recommended workflow with vdist to be sure I'm using it right, but examining its source and testing its behaviour I'm still having some doubts:
- Why is generated a virtualenv through packaging process if it doesn't seem to be used neither in packaging process nor after installation? (python interpreter directly used is the one freshly compiled, so I don't get what value has to run a virtualenv here).
- Why project folder (kind of a _source_ directory) is included in package when application apparently can be run from what's installed in /opt/vdist-python/lib/python3.4/site-packages (kind of a _compiled_ form of the application)?. I mean that in my particular use case I could entirely omit _/opt/geolocate_ folder and just install _/opt/vdist-python_ and my application could be entirely runnable just running a post-install script to be sure my entry point would be properly linked from /usr/bin.

**Comment by objectified** [comment]
Both your questions are assuming a scenario where a setup.py is actually used. In many cases, it is not used. Typically reusable modules provide a setup.py, but standalone applications typically do not. I decided to perform a `python setup.py install` just because your application might require entry points to be present in some cases. In these cases - yes, the application is running from the "installed" location. Making a distinction between those two cases might be more pure, but I'm not sure if that's worth the effort given that the number of applications packaged with vdist that actually provide a setup.py might be fairly minimal. I'm assuming that reusable modules often end up in a PyPI repository/Conda channel or what have you. Of course it is _possible_ to package reusable Python modules with vdist, it has never been its goal. The goal of vdist is to provide isolated packages that can be deployed on their own.

The Python packaging and deployment ecosystem is quite messy. I'm not trying to solve all of its problems, but I created vdist to get rid of the pain of depending on OS provided libraries and having to do pip installs on production machines.

**Comment by dante-signal31** [comment]
Thanks for the reply.

I've been packaging my application for a relatively short time so I don't understand entirely why you say that standalone applications typically don't use setup.py. Do you mean that standalone applications don't use to be uploaded to PyPI?. My application ([geolocate](https://github.com/dante-signal31/geolocate)) is a standalone one but it has a setup.py to be packaged for PyPI.

In any case, I'm going to modify code to implement the two use cases:
- If there is a setup.py (let's call it "setup mode"), run it but include in package just the _installed_ location (compiled python folder).
- If there is no setup.py (let's call it "dir mode"), include both folders: project folder and compiled python one.

I'll send you a PR for your consideration.

**Comment by objectified** [comment]
Well, by "standalone applications" I suppose I mean "applications that are not shipped as reusable modules", meaning the typical internal web and backend applications inside a company, for example. There are definitely modules that can be run as stand alone applications (Ansible, Fabric, things like that) that do have a setup.py provided. For end user applications that do not get reused as modules, it wouldn't be as useful to have them uploaded as pip modules (instead, you want OS packages to install those, right?)

That's great, your contributions are much appreciated! And also, please keep asking critical questions like you are doing, it's important to rethink and reevaluate all the time.

**Comment by dante-signal31** [comment]
As I've created a [PR](https://github.com/objectified/vdist/pull/7) to solve topic discussed in this issue, I'm closing this issue assuming new info will be included in PR comments.
