### ISSUE TITLE
Read The Docs documentation does not include usecases.md

### ISSUE THREAD

**Issue by dante-signal31** [objectified/vdist#8]
Hi @objectified,

I was reviewing documentation and I've found that usecases.md has not been uploaded to [RedTheDocs](https://vdist.readthedocs.io/en/latest/). In fact,[ "how to use" section](https://vdist.readthedocs.io/en/latest/howtouse/) is updated in ReadTheDocs but includes a link to "use cases" that is actually dead.

Regards

**Comment by objectified** [comment]
This was caused by mkdocs.yml not being adjusted yet. I've added the usecases.md file to mkdocs.yml (bff1c66b3f9d7e75ae76a4c5214f44503d19b), made a few minor changes, and things are looking good again. Thanks for noticing!
